feat: Bump hey changes

diff --git a/bin/hey b/bin/hey
--- a/bin/hey
+++ b/bin/hey
@@ -1,14 +1,17 @@
 #!/usr/bin/env zsh
 
-# I don't believe the interface for Nix's utility scripts are very good. Guix's,
-# on the other hand, is excellent. Management of your OS is done by a single
-# program with simpler, more intuitive commands. This script is a rudimentary
-# attempt at giving me that.
+# I don't like the user story for Nix's binaries, unlike Guix's.  So I wrote
+# this to abstract away the unneeded complexity for everyday maintenance of my
+# NixOS config.
 #
-#   hey cd|check      -> nix flake check $DOTFILES
-#   hey sh|show       -> nix flake show $DOTFILES
-#   hey u|update      -> nix flake update --recreate-lock-file $DOTFILES
-#   hey re|rebuild    -> nixos-rebuild --flake $DOTFILES#$HOST ${1:-build}
+#   hey cd|check
+#     nix flake check $DOTFILES
+#   hey sh|show
+#     nix flake show $DOTFILES
+#   hey u|update [INPUT...]
+#     nix flake update --recreate-lock-file $DOTFILES
+#   hey re|rebuild [ARGS...]
+#     nixos-rebuild --flake $DOTFILES#$HOST ${@:-build}
 #   hey t|test        -> nixos-rebuild --flake $DOTFILES#$HOST --fast test
 #   hey theme $THEME  -> THEME=$THEME hey test (quick theme swapping)
 #   hey rollback      -> hey rebuild --rollback switch
@@ -22,7 +25,7 @@
 #   hey up|upgrade    -> hey update && hey rebuild switch
 #   hey gc            -> GC user profile, optimise nix store
 #   sudo hey gc       -> GC, optimise nix store, & delete old boot entries
-#   hey push REMOTE   -> push flake to remote (over SSH) and rebuild remotely
+#   hey push REMOTE   -> 1. Build machine locally, 2. Copy result to remote, 3. Activate config on remote
 #   hey gen|generations -> explore, manage, diff across generations (WIP)
 #
 # hey (with no sub-command) can also be used as an alternative to nix-env:
@@ -32,8 +35,14 @@
 #   hey -e htop
 
 set -e
-REMOTE=${REMOTE:-"~/.config/dotfiles"}
-DOTFILES="${0:a:h}/.."
+if [[ -z $FLAKE ]]; then
+  for dir in /etc/nixos /etc/dotfiles; do
+    if [[ -f "$dir/flake.nix" ]]; then
+      FLAKE=$dir
+      break
+    fi
+  done
+fi
 
 #
 function main {
@@ -61,8 +70,12 @@ function main {
 
   function _rebuild {
     # Move to $DOTFILES to prevent polluting the system with result links
-    pushd $DOTFILES >/dev/null
-    _do sudo nixos-rebuild --flake ".#$HOST" ${@:-build}
+    pushd $FLAKE >/dev/null
+    # REVIEW Use --impure instead when it's in a stable release of nix
+    _do ${SUDO:+sudo} nixos-rebuild \
+      --flake "${FLAKE}#${HOSTNAME:-$HOST}" \
+      --option pure-eval no \
+      ${@:-build}
     popd >/dev/null
   }
 
@@ -70,24 +83,27 @@ function main {
     echo "Updating NixOS flake"
     if [[ "$@" ]]; then
       for flake in $@; do
-        _do nix flake update --update-input "$flake" "$DOTFILES"
+        _do nix flake update --update-input "$flake" "$FLAKE"
       done
     else
-      _do nix flake update --recreate-lock-file "$DOTFILES"
+      _do nix flake update --recreate-lock-file "$FLAKE"
     fi
   }
 
   function _gc {
     if [[ $EUID == 0 ]]; then
       echo "Cleaning up your system..."
-      _do sudo nix-collect-garbage ${@:--d}
+      _do nix-collect-garbage ${@:--d}
       _do nix-store --optimise
+      # Clear out left-over secrets. The switch-to-configuration call below will
+      # regenerate them.
+      [[ -d /run/secrets ]] && _do rm -f /run/secrets/*
       # nix-collect-garbage is a Nix tool, not a NixOS tool. It won't delete old
       # boot entries until you do a nixos-rebuild (which means we'll always have
       # 2 boot entries at any time). Instead, we properly delete them by
       # reloading the current environment.
-      _do sudo nix-env --delete-generations old --profile /nix/var/nix/profiles/system
-      _do sudo /nix/var/nix/profiles/system/bin/switch-to-configuration switch
+      _do nix-env --delete-generations old --profile /nix/var/nix/profiles/system
+      _do /nix/var/nix/profiles/system/bin/switch-to-configuration switch
     else
       echo "Cleaning up your user profile..."
       _do nix-collect-garbage ${@:--d}
@@ -127,31 +143,56 @@ function main {
   }
 
   ###
+  eval set -- $(getopt -n hey -o df:h:ieAqp -l dryrun,flake:,host: -- "$@")
+  while :
+  do
+    case "$1" in
+      -d|--dryrun) DRYRUN=1;    shift   ;;
+      -f|--flake)  FLAKE=$2;    shift 2 ;;
+      -h|--host)   HOSTNAME=$2; shift 2 ;;
+      -i|-A|-q|-e|-p) _do nix-env "$@"; exit 0 ;;
+      --) shift; break ;;
+    esac
+  done
+  if [[ ! -d $FLAKE ]]; then
+    >&2 echo "Couldn't find flake.nix in $FLAKE"
+    exit 1
+  fi
+
   cmd="$1"
   [[ $# > 0 ]] && shift
   case "$cmd" in
-    # TODO Repl/shell for nixos+dotfiles
-    # sh|shell)    _do nix-shell "$@"             ;;
-    # repl)        _do nix develop "$@"           ;;
+    sh|shell)    _do nix develop "$FLAKE" "$@" ;;
+    repl)        _do nix repl "$FLAKE/flake.nix" "<nixpkgs>" "$@" ;;
 
-    ch|check)    _do nix flake check "$@" "$DOTFILES";;
-    sh|show)     _do nix flake show "$@" "$DOTFILES" ;;
+    ch|check)    _do nix flake check "$@" "$FLAKE"      ;;
+    sh|show)     _do nix flake show "$@" "$FLAKE"       ;;
 
-    theme)       THEME="$1" _rebuild --fast test ;;
-    t|test)      _rebuild --fast test "$@"      ;;
-    re|rebuild)  _rebuild "${@:-switch}"        ;;
-    rollback)    _rebuild --rollback switch     ;;
-    vm)          _rebuild "$@" vm               ;;
+    theme)       THEME="$1" SUDO=1 _rebuild --fast test ;;
+    t|test)      SUDO=1 _rebuild --fast test "$@"       ;;
+    re|rebuild)  SUDO=1 _rebuild "${@:-switch}"         ;;
+    rollback)    SUDO=1 _rebuild --rollback switch      ;;
+    vm)          SUDO=1 _rebuild "$@" vm                ;;
 
-    u|update)    _update "$@"                   ;;
-    up|upgrade)  _update && _rebuild switch     ;;
-    s|search)    nix search nixpkgs "$@"        ;;
+    u|update)    _update "$@"                           ;;
+    up|upgrade)  _update && SUDO=1 _rebuild switch      ;;
+    s|search)    nix search nixpkgs "$@"                ;;
 
-    swap)        _swap $@                       ;;
-    gc)          _gc "$@"                       ;;
+    swap)        _swap "$@" ;;
+    gc)          _gc "$@" ;;
     push)
-      rsync -avzh ./ "$1:$REMOTE/"
-      ssh -t -l "$USERNAME" "$1" "$REMOTE/bin/hey re" "${@[2,-1]}"
+      target=$1
+      cmd=${2:-test}
+      echo "Enabling root ssh access on $target"
+      if _do ssh -t "$target" "sudo mkdir -p /root/.ssh && sudo cp -f ~/.ssh/authorized_keys /root/.ssh/authorized_keys"; then
+        trap '_do ssh -t "root@$target" "rm -f /root/.ssh/authorized_keys"' EXIT
+        echo "Building $target ($cmd)"
+        HOSTNAME="${HOSTNAME:-$target}" _rebuild \
+          --build-host localhost \
+          --target-host "root@$target" \
+          $cmd
+        echo "Undoing root ssh access on $target"
+      fi
       ;;
 
     gen|generations)
@@ -174,11 +215,14 @@ function main {
       esac
       ;;
 
-    h|help|-h|--help) _usage ;;
-    -*) _do nix-env "$cmd" "$@" ;;
+    h|help) _usage ;;
     "") _usage ;;
-    *)  echo "Couldn't find command: $cmd" 1>&2
-        exit 1
+    *)  if command -v hey-$cmd >/dev/null; then
+          hey-$cmd $@
+        else
+          echo "Couldn't find command: $cmd" 1>&2
+          exit 1
+        fi
         ;;
   esac
 }
